# Generated by Django 2.0 on 2019-12-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='customer_name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='expiry_date',
            new_name='edate',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='manufacture_date',
            new_name='mdate',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='no_of_products',
            new_name='npros',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='product_class',
            new_name='pclass',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='product_cost',
            new_name='pcost',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='product_id',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='product_name',
            new_name='pname',
        ),
    ]
